package com.founder.bbc.webinterface.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2016-04-01T16:20:40.493+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "ATGtoBBCServicePublishImplService", 
                  wsdlLocation = "http://popproxy.bbcuat.com/ws/ATG?wsdl",
                  targetNamespace = "http://webservice.webInterface.bbc.founder.com/") 
public class ATGtoBBCServicePublishImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.webInterface.bbc.founder.com/", "ATGtoBBCServicePublishImplService");
    public final static QName ATGtoBBCServicePublishImplPort = new QName("http://webservice.webInterface.bbc.founder.com/", "ATGtoBBCServicePublishImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://popproxy.bbcuat.com/ws/ATG?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ATGtoBBCServicePublishImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://popproxy.bbcuat.com/ws/ATG?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ATGtoBBCServicePublishImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ATGtoBBCServicePublishImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ATGtoBBCServicePublishImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ATGtoBBCServicePublishImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ATGtoBBCServicePublishImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ATGtoBBCServicePublishImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ATGtoBBCServicePublish
     */
    @WebEndpoint(name = "ATGtoBBCServicePublishImplPort")
    public ATGtoBBCServicePublish getATGtoBBCServicePublishImplPort() {
        return super.getPort(ATGtoBBCServicePublishImplPort, ATGtoBBCServicePublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ATGtoBBCServicePublish
     */
    @WebEndpoint(name = "ATGtoBBCServicePublishImplPort")
    public ATGtoBBCServicePublish getATGtoBBCServicePublishImplPort(WebServiceFeature... features) {
        return super.getPort(ATGtoBBCServicePublishImplPort, ATGtoBBCServicePublish.class, features);
    }

}
